_BASE_: "600.yaml"

DATASETS:
  TRAIN: ("dota_1_train_1024",)
  TEST: ("dota_1_val_1024",)

INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  MIN_SIZE_TEST: 1024


SOLVER:
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 2000

  AUG:
    ENABLED: False
    MIN_SIZES: (256, 512, 756, 1024, 1536)
    MAX_SIZE: 1536
    FLIP: True
